//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendXEntities : DbContext
    {
        public AttendXEntities()
            : base("name=AttendXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_SubjectMaster> T_SubjectMaster { get; set; }
        public virtual DbSet<T_UserMaster> T_UserMaster { get; set; }
        public virtual DbSet<T_AttendanceRecordMaster> T_AttendanceRecordMaster { get; set; }
        public virtual DbSet<T_StudentsAccountMaster> T_StudentsAccountMaster { get; set; }
        public virtual DbSet<T_SubjectEnrollment> T_SubjectEnrollment { get; set; }
    }
}
