//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectEnrollment
    {
        public int EnrollmentID { get; set; }
        public int EDPCode { get; set; }
        public int Status { get; set; }
    }
}
