//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AttendanceRecordMaster
    {
        public int arm_AttendanceID { get; set; }
        public Nullable<int> arm_ID { get; set; }
        public Nullable<int> arm_EnrollmentID { get; set; }
        public Nullable<System.DateTime> arm_Date { get; set; }
        public Nullable<System.TimeSpan> arm_TimeIn { get; set; }
        public Nullable<System.TimeSpan> arm_TimeOut { get; set; }
    }
}
