//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StudentsAccountMaster
    {
        public int sam_ID { get; set; }
        public string sam_Firstname { get; set; }
        public string sam_Lastname { get; set; }
        public string sam_Gender { get; set; }
        public string sam_Course { get; set; }
        public string sam_Year { get; set; }
        public string sam_SchoolYear { get; set; }
        public string sam_Semester { get; set; }
        public byte[] sam_Photo { get; set; }
    }
}
