//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SubjectMaster
    {
        public int sm_EDPCode { get; set; }
        public string sm_Title { get; set; }
        public string sm_SubjectCode { get; set; }
        public int sm_Units { get; set; }
        public string sm_Schedule { get; set; }
        public string sm_StartTime { get; set; }
        public string sm_EndTime { get; set; }
        public string sm_Course { get; set; }
    }
}
