//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendX___QRCode_Based_Attendance_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserMaster
    {
        public int um_ID { get; set; }
        public string um_Username { get; set; }
        public string um_Password { get; set; }
        public string um_Firstname { get; set; }
        public string um_Lastname { get; set; }
        public string um_Grant { get; set; }
        public string um_Status { get; set; }
    }
}
